## Numpy

to install numpy goto terminal and type<br>
sudo pip3.6 install numpy

In [1]:
#if no output comes then the installation is successful
import numpy

In [3]:
#array basics
import numpy as np      #np is just as a nick name for numpy
a=np.array([1,2,3])     #Create a rank 1 array
print(type(a))          #Prints <class 'numpy.ndarray'>
print(a.shape)          #Prints "(3,)" #rows vs columns
print(a[0],a[1],a[2])   #Prints "1 2 3"
a[0]=5                  #Change an element of the array
print(a)                #Prints "[5 2 3]"

"""
EXPLANATION:- 
"""

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [5]:
# 1 row 3 column
d=np.array([1,2,3])
print(d.shape)

#3 row 1 column
e=np.array([[1],[2],[3]])
print(e.shape)

(3,)
(3, 1)


In [6]:
#another example 2 by 3 matrix
b=np.array([[2,3,4],[4,5,6]])
print(b.shape)
print(b[0,0],b[1,0])


(2, 3)
2 4


In [9]:
#create numpy array from python list
list1=[[1,2,3],[4,5,6],[7,8,9]]
f=np.array(list1)
print("shape is ",f.shape)
print(f)
print(f[1,2],f[2,1])

shape is  (3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
6 8


In [11]:
#create an array of zeros using np.zeros((row,column))
a=np.zeros((2,2))
print(a)
print(type(a[0][0])) #numpy float for 64 bit precision

[[0. 0.]
 [0. 0.]]
<class 'numpy.float64'>


In [12]:
#create an array of ones using np.ones((row,column))
a=np.ones((2,3))
print(a)
print(type(a[0][0])) #numpy float for 64 bit precision

[[1. 1. 1.]
 [1. 1. 1.]]
<class 'numpy.float64'>


In [17]:
#create an full array of any constant using np.full((row,column),constant)
a=np.full((2,3),7)  #can accept int float str
print(a)
print(type(a[0][0])) #numpy float for 64 bit precision

[[7 7 7]
 [7 7 7]]
<class 'numpy.int64'>


In [19]:
#create an identity matrix using np.eye(row or column)
a=np.eye(2)  #can accept int float str
print(a)
print(type(a[0][0])) #numpy float for 64 bit precision

[[1. 0.]
 [0. 1.]]
<class 'numpy.float64'>


In [21]:
#create an identity matrix using np.eye(row or column) #try uneven dimension. it just creates the minm possible quare matrix and rest are assigned zeros
a=np.eye(2,4)  #can accept int float str
print(a)
print(type(a[0][0])) #numpy float for 64 bit precision

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]]
<class 'numpy.float64'>


In [23]:
#create a random matrix by using np.random.random((rows,columns))
e=np.random.random((2,3)) #random is a function of random class of numpy library
print(e)

[[0.39938407 0.83708767 0.96025876]
 [0.51130927 0.90703921 0.20193857]]


In [25]:
#create an array of zeros using np.zeros((row,column))
a=np.zeros((4,3))
print(a)
print(type(a[0][0])) #numpy float for 64 bit precision

#create an array of ones using np.ones((row,column))
b=np.ones((4,3))
print(b)
print(type(b[0][0])) #numpy float for 64 bit precision

#create an full array of any constant using np.full((row,column),constant)
c=np.full((4,3),8.5)  #can accept int float str
print(c)
print(type(c[0][0])) #numpy float for 64 bit precision

#create an identity matrix using np.eye(row or column)
d=np.eye(4)  #can accept int float str
print(a)
print(type(d[0][0])) #numpy float for 64 bit precision

#create a random matrix by using np.random.random((rows,columns))
e=np.random.random((4,3)) #random is a function of random class of numpy library
print(e)
print(type(e[0][0])) #numpy float for 64 bit precision

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.float64'>
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
<class 'numpy.float64'>
[[8.5 8.5 8.5]
 [8.5 8.5 8.5]
 [8.5 8.5 8.5]
 [8.5 8.5 8.5]]
<class 'numpy.float64'>
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.float64'>
[[0.76083214 0.51232813 0.72161008]
 [0.65210889 0.60642732 0.62307544]
 [0.63113996 0.50483654 0.02826654]
 [0.10755468 0.10444478 0.01576409]]
<class 'numpy.float64'>


### Array Indexing

Numpy offers several ways to index into arrays <br> Slicing: Similar to python lists,numpy arrays can be sliced. Since arrays may be multidimensional,you must specify a slice for each dimension of the array.<br> while slicing any chnage you make to the sliced(child) array it is reflected in the parent too.

In [28]:
import numpy as np
#Create the following rank 2 array with shape(3,4)
#[[1 2 3 4] [5 6 7 8] [9 10 11 12]]

a=np.array([[1, 2, 3 ,4],[5 ,6, 7, 8],[9 ,10 ,11 ,12]])

#use slicing to pull out the sub array consisting of the first 
#and columns 1 and 2; b is the following array of shape(2,2)
#[[2 3] [6 7]]
b=a[:2,1:3] # for :2 it will consider 0 and 1 rows of a, column will be 1:3 ie 1 and 2 
print(b)

#A slice of an array is a view into the same data,so modifying the sliced array 
#will modify the original array
print(a[0][1])  #check before
b[0][0]=77      #chnage the value in sliced array
print(a[0][1])  #it is reflected in original array

[[ 6  7]
 [10 11]]


In [33]:
#Exercise
arr1=np.array([[3,7,2,10],[4,2,10,22],[3,6,15,21]])
arr2=arr1[1:3,1:3]
print(d)
print(arr1[2,2])
arr2[1][1]=30
print(arr1[2,2])

[[ 2 10]
 [ 6 15]]
15
30


One useful trick with integer array indexing is selecting or mutating<br>one element from each row of a matrix

In [40]:
import numpy as np
#Create a new array from which we will select elements
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)

#create an array of indices
b=np.array([0,2,0,1]) #has to be numpy array. list gives

#select one element from each row of "a" using indices in b
print(a[np.arange(4),b])

#EXPLANATION:- here we want to extract certain elements(here it is four) from a into another array(not defined in this problem)
#np.arange(4) gives an array [0,1,2,3] . b is an array [0,2,0,1]. 
#ofc it is obvious that length of np.arange(4) should be euqal with b 
#Now what happens is,it maps from row to column like from np.range(4)-->b (0,0) (1,2) (2,0) (3,1)
#from the above mentioned addresses the elements are accessed into a temporary array.
#in case of error IndexError is found

a[np.arange(4),b]+=10
#change all the previous elements by adding 10
#a[b,np.arange(4)]+=10 #index error
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [41]:
#Exercise
# take the array [23,34,56],[-2,-13,12],[-14,20,16] add 25 to 23,-13,-14
a=np.array([[23,34,56],[-2,-13,12],[-14,20,16]])
col=np.array([0,1,0])
print(a)
print(a[np.arange(3),col])
a[np.arange(3),col]+=25
print(a)


[[ 23  34  56]
 [ -2 -13  12]
 [-14  20  16]]
[ 23 -13 -14]
[[48 34 56]
 [-2 12 12]
 [11 20 16]]


### Boolean Array Indexing

<b>Boolean array indexing:</b> Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfies some condition.

In [45]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
bool_idx=(a>2) 
#bool_idx is a amtrix of true or false of size same as that of "a". 
#it just holds true/false at the same slot of "a" 
#depending whether the element has satisfied the condition or not
print(type(bool_idx),bool_idx)

#we use boolean array indexing to construct a rank 1 array
#consisting of the elements of a corresponding true value
#of bool_idx
print(a[bool_idx]) #prints "[3 4 5 6]"

#we can do all the above in a single concise statement:
print(a[a>2]) #prints "[3 4 5 6]"

#print all the elements ;less than 3
print("elements less than 3 are",a[a<3])

<class 'numpy.ndarray'> [[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]
elements less than 3 are [1 2]


### Array Math
basic mathematical functions operate element wise on arrays and are available<br>both as operator overloads and as functions in the numpy module

In [51]:
import numpy as np
x=np.array([[1,2],[3,4]] , dtype=np.float64)
y=np.array([[5,6],[7,8]] , dtype=np.float64)

#Element wise sum; both produce the array
print("sum")
print(x+y)
print(np.add(x,y))

#Element wise difference; both produce the array
print("subtract")
print(x-y)
print(np.subtract(x,y))

#Element wise product; both produce the array
print("multiply")
print(x*y)
print(np.multiply(x,y))

#Element wise division; both produce the array
print("division")
print(x/y)
print(np.divide(x,y))

#Element wise sqrt; both produce the array
print("division")
print(x**0.5)
print(np.sqrt(x))

#single number operation
print("mul",x*4)
print("add",x+4)
print("sub",x-4)
print("div",x/4)


sum
[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
subtract
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
multiply
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
division
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
division
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
mul [[ 4.  8.]
 [12. 16.]]
add [[5. 6.]
 [7. 8.]]
sub [[-3. -2.]
 [-1.  0.]]
div [[0.25 0.5 ]
 [0.75 1.  ]]


<b>Dot and Cross Multiplication </b>

In [53]:
import numpy as np
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print(np.dot(x,y))
print(np.dot(y,x))


[[19 22]
 [43 50]]
[[23 34]
 [31 46]]


<b>Sum of matrix in numpy</b>

In [54]:
import numpy as np
x=np.array([[1,2],[3,4]])
print(np.sum(x))        #sum of all the elements
print(np.sum(x,axis=0)) #of each column
print(np.sum(x,axis=1)) #of each row

10
[4 6]
[3 7]


<b>Transpose of matrix</b>

In [55]:
import numpy as np
x=np.array([[1,2],[3,4]])
print(x)
print(x.T) #x.t creates thetranspose of the matrix here T is the keyword

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


## Worksheet

<b>Q1. X = 3A - 4B</b><br>

<b>A:</b><br>
4 -2<br>
1 -7<br>

<b>B:</b><br>
-1 2<br>
6 5<br>

Solve for <b>X</b>

In [56]:
#ques1
import numpy as np
a=np.array([[4,-2],[1,-7]])
b=np.array([[-1,2],[6,5]])
a=3*a
b=4*b
x=a-b
print(x)

[[ 16 -14]
 [-21 -41]]


<b>Q2. X = A'A - 2A</b><br>

<b>A:</b><br>
3 -1<br>
0 2<br>

Solve for <b>X</b><br>
correction inQ2

In [58]:
#ques2
import numpy as np
a=np.array([[3,-1],[0,2]])
x=np.dot((a.T),a)
x=x-(2*a)
print(x)

[[ 3 -1]
 [-3  1]]


<b>Q3. X = 2AB + C</b><br>

<b>A:</b><br>
3 0 -1<br>
0 2 1<br>

<b>B:</b><br>
1 2<br>
1 0<br>
0 6<br>

<b>C:</b><br>
-2 0<br>
-2 -5<br>

Solve for <b>X</b><br>

In [59]:
#ques3
import numpy as np
a=np.array([[3,0,-1],[0,2,1]])
b=np.array([[1,2],[1,0],[0,6]])
c=np.array([[-2,0],[-2,-5]])
ab=2*np.dot(a,b)
x=ab+c
print(x)


[[4 0]
 [2 7]]


<b>Q4. Proof the following using the given matrices:</b><br>

<b>A:</b><br>
10 12<br>
-7 -21<br>

<b>B:</b><br>
45 3<br>
12 -2<br>

<b>B:</b><br>
20 21<br>
-4 -5<br>

<b>i) (ABC)' = A'B'C'</b><br>
<b>ii) (A + B)' = A' + B'</b><br>
<b>iii) A(B + C) = AB + AC</b><br>

In [67]:
#ques4
a=np.array([[10,12],[-7,-21]])
b=np.array([[45,3],[12,-2]])
c=np.array([[20,21],[-4,-5]])

#i) (ABC)' = A'B'C'
abc=np.dot(np.dot(a,b),c)
abc1=np.dot(np.dot(a.T,b.T),c.T)
print(np.array_equal(abc.T,abc1.T))
#
#ii) (A + B)' = A' + B'
asb=(a+b).T
ab=a.T+b.T
print(np.array_equal(asb,ab))

#iii) A(B + C) = AB + AC

first=np.dot(a,b+c)
second=np.dot(a,b)+np.dot(a,c)
print(np.array_equal(first,second))


False
True
True


In [68]:
a=np.array([[10,12],[-7,-21]])
b=np.array([[45,3],[12,-2]])
print(a==b)

[[False False]
 [False False]]
